wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723103120
    t:
      1:
      - 1
      - 41
      - 55
      - 80
      2:
      - 1
      - 41
      - 55
      - 80
      3:
      - 19
      - 23
      - 33
      4: 3.12.4
      5: 0.17.5
      8:
      - 5
      13: darwin-x86_64
input_datasets:
  desc: null
  value:
  - Dataset: hub://activeloop/coco-train
    Commit ID: 4d907b9edb2e5edb939abdb3748e131b7163d848
    URL: https://app.activeloop.ai/activeloop/coco-train/4d907b9edb2e5edb939abdb3748e131b7163d848
